# network parameters
embedding_size : &embedding_size 128
channel_last: &channel_last false
network: r50
network_kwargs:
  dropout: 0.0
  embedding_size: *embedding_size
  channel_last: *channel_last
head: "arcface"
sample_rate: 1

# train options
model_parallel: false
fp16: false
is_graph: true
is_global: true
resume: false
scale_grad: false

# hyper parameters
lr: 0.1
momentum: 0.9
decay_epoch: [11, 17, 22]
batch_size: 128
num_epoch: 25
warmup_epoch: -1
weight_decay: 0.0005

# log parameters
log_frequent: 50

# data parameters
dataset: ms1m-retinaface-t1
num_classes: 93431
num_image: 5179510
ofrecord_path: /workspace/data/insightface/ms1m-retinaface-t1/ofrecord
ofrecord_part_num: 8
output: ms1mv3_arcface_r50
synthetic: false
use_gpu_decode: false
val_frequence: 6000
val_image_num: 
    agedb_30: 12000
    cfp_fp: 14000
    lfw: 12000
#   state:
#     agedb_30: 12000
#     cfp_fp: 14000
#     lfw: 12000
val_targets:
- lfw
- cfp_fp
- agedb_30

train_num: 100000